project_id = "czzuabqrtrostojxsxwb"

[functions.meta-auth-url]
verify_jwt = false

[functions.meta-oauth]
verify_jwt = false

[functions.meta-publish]
verify_jwt = false

[functions.meta-comments]
verify_jwt = false

[functions.meta-webhook]
verify_jwt = false

[functions.process-scheduled-posts]
verify_jwt = false

[functions.save-manual-token]
verify_jwt = false

[functions.tiktok-auth-url]
verify_jwt = false

[functions.tiktok-oauth]
verify_jwt = false
